stages:
- name: setting
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |
        npm install
- name: docker build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: jonginout/hello-world-express:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/express-app-deployment.yaml
timeout: 60
